name: "Dependabot auto-merge"
description: "Approves and merges Dependabot PRs"


inputs:
  github_token:
    description: "GitHub token used for commenting on and approving PR"
    required: true

runs:
  using: "composite"
  steps:
      - name: approve-and-request-merge
        uses: actions/github-script@v5.0.0
        with:
          script: |
            const opts = github.rest.pulls.listReviews.endpoint.merge({
              pull_number: context.payload.pull_request.number,
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
            });
            const reviews = await github.paginate(opts);
            const ourReview = reviews.find(
              (review) =>
                review.state === "APPROVED" && review.user.login === "contentful-automation[bot]"
            );
            if (ourReview) {
              console.log(
                `The user "${mergeComment.user.login}" has already approved and requested this PR is merged, exiting`
              );
              return;
            }
            github.rest.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
              body: ''
            })

          github-token: ${{ inputs.github_token }}
      - run: gh pr merge -ds --auto
          env: ${{ inputs.github_token }}
          